theme: jekyll-theme-minimal
title: Adarsh Pritam
description: Adarsh Pritam is an MSc student in Data Science. His research interests lie in machine learning, computer vision, natural language processing, and healthcare applications. Previously, he obtained his Bachelor's degree in Mathematics and Statistics from Bangalore University. Expected graduation in June 2026.
